using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Automation.Service.ViewModel
{
    public class TestScriptVM : BaseEntityVM
    {
        public string TestCaseID { get; set; }
        public string TCStepID { get; set; }
        public string TestScriptName { get; set; }
        public string FunctionDescription { get; set; }
        public string FunctionName { get; set; }
        public string Run { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
        public string Param4 { get; set; }
        public string Param5 { get; set; }
        public string Param6 { get; set; }
        public string Param7 { get; set; }
        public string Param8 { get; set; }
        public string Param9 { get; set; }
        public string Param10 { get; set; }
        public string Param11 { get; set; }
        public string Param12 { get; set; }
        public string Param13 { get; set; }
        public string Param14 { get; set; }
        public string Param15 { get; set; }
        public string Param16 { get; set; }
        public string Param17 { get; set; }
        public string Param18 { get; set; }
        public string Param19 { get; set; }
        public string Param20 { get; set; }
        public string Param21 { get; set; }
        public string Param22 { get; set; }
        public string Param23 { get; set; }
        public string Param24 { get; set; }
        public string Param25 { get; set; }
        public string Param26 { get; set; }
        public string Param27 { get; set; }
        public string Param28 { get; set; }
        public string Param29 { get; set; }
        public string Param30 { get; set; }
        public string Param31 { get; set; }
        public string Param32 { get; set; }
        public string Param33 { get; set; }
        public string Param34 { get; set; }
        public string Param35 { get; set; }
        public string Param36 { get; set; }
        public string Param37 { get; set; }
        public string Param38 { get; set; }
        public string Param39 { get; set; }
        public string Param40 { get; set; }
        public string Param41 { get; set; }
        public string Param42 { get; set; }
        public string Param43 { get; set; }
        public string Param44 { get; set; }
        public string Param45 { get; set; }
        public string Param46 { get; set; }
        public string Param47 { get; set; }
        public string Param48 { get; set; }
        public string Param49 { get; set; }
        public string Param50 { get; set; }
        public string Param51 { get; set; }
        public string Param52 { get; set; }
        public string Param53 { get; set; }
        public string Param54 { get; set; }
        public string Param55 { get; set; }
        public string Param56 { get; set; }
        public string Param57 { get; set; }
        public string Param58 { get; set; }
        public string Param59 { get; set; }
        public string Param60 { get; set; }
        public string Param61 { get; set; }
        public string Param62 { get; set; }
        public string Param63 { get; set; }
        public string Param64 { get; set; }
        public string Param65 { get; set; }
        public string Param66 { get; set; }
        public string Param67 { get; set; }
        public string Param68 { get; set; }
        public string Param69 { get; set; }
        public string Param70 { get; set; }
        public string Param71 { get; set; }
        public string Param72 { get; set; }
        public string Param73 { get; set; }
        public string Param74 { get; set; }
        public string Param75 { get; set; }
        public string Param76 { get; set; }
        public string Param77 { get; set; }
        public string Param78 { get; set; }
        public string Param79 { get; set; }
        public string Param80 { get; set; }
        public string Param81 { get; set; }
        public string Param82 { get; set; }
        public string Param83 { get; set; }
        public string Param84 { get; set; }
        public string Param85 { get; set; }
        public string Param86 { get; set; }
        public string Param87 { get; set; }
        public string Param88 { get; set; }
        public string Param89 { get; set; }
        public string Param90 { get; set; }
        public string Param91 { get; set; }
        public string Param92 { get; set; }
        public string Param93 { get; set; }
        public string Param94 { get; set; }
        public string Param95 { get; set; }
        public string Param96 { get; set; }
        public string Param97 { get; set; }
        public string Param98 { get; set; }
        public string Param99 { get; set; }
        public string Param100 { get; set; }
        public string Module { get; set; }
        public int StatusID { get; set; }
        public int CUDStatusID { get; set; }
        public bool? IsLocked { get; set; }
        public int? LockedByUser { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public int? UserId { get; set; }
    }

    public class TestScript_MapVM: BaseEntityVM
    {
        public int MasterTestScriptID { get; set; }
        public string TestCaseID { get; set; }
        public string TCStepID { get; set; }
        public string TestScriptName { get; set; }
        public string FunctionDescription { get; set; }
        public string FunctionName { get; set; }
        public string Run { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public string Param3 { get; set; }
        public string Param4 { get; set; }
        public string Param5 { get; set; }
        public string Param6 { get; set; }
        public string Param7 { get; set; }
        public string Param8 { get; set; }
        public string Param9 { get; set; }
        public string Param10 { get; set; }
        public string Param11 { get; set; }
        public string Param12 { get; set; }
        public string Param13 { get; set; }
        public string Param14 { get; set; }
        public string Param15 { get; set; }
        public string Param16 { get; set; }
        public string Param17 { get; set; }
        public string Param18 { get; set; }
        public string Param19 { get; set; }
        public string Param20 { get; set; }
        public string Param21 { get; set; }
        public string Param22 { get; set; }
        public string Param23 { get; set; }
        public string Param24 { get; set; }
        public string Param25 { get; set; }
        public string Param26 { get; set; }
        public string Param27 { get; set; }
        public string Param28 { get; set; }
        public string Param29 { get; set; }
        public string Param30 { get; set; }
        public string Param31 { get; set; }
        public string Param32 { get; set; }
        public string Param33 { get; set; }
        public string Param34 { get; set; }
        public string Param35 { get; set; }
        public string Param36 { get; set; }
        public string Param37 { get; set; }
        public string Param38 { get; set; }
        public string Param39 { get; set; }
        public string Param40 { get; set; }
        public string Param41 { get; set; }
        public string Param42 { get; set; }
        public string Param43 { get; set; }
        public string Param44 { get; set; }
        public string Param45 { get; set; }
        public string Param46 { get; set; }
        public string Param47 { get; set; }
        public string Param48 { get; set; }
        public string Param49 { get; set; }
        public string Param50 { get; set; }
        public string Param51 { get; set; }
        public string Param52 { get; set; }
        public string Param53 { get; set; }
        public string Param54 { get; set; }
        public string Param55 { get; set; }
        public string Param56 { get; set; }
        public string Param57 { get; set; }
        public string Param58 { get; set; }
        public string Param59 { get; set; }
        public string Param60 { get; set; }
        public string Param61 { get; set; }
        public string Param62 { get; set; }
        public string Param63 { get; set; }
        public string Param64 { get; set; }
        public string Param65 { get; set; }
        public string Param66 { get; set; }
        public string Param67 { get; set; }
        public string Param68 { get; set; }
        public string Param69 { get; set; }
        public string Param70 { get; set; }
        public string Param71 { get; set; }
        public string Param72 { get; set; }
        public string Param73 { get; set; }
        public string Param74 { get; set; }
        public string Param75 { get; set; }
        public string Param76 { get; set; }
        public string Param77 { get; set; }
        public string Param78 { get; set; }
        public string Param79 { get; set; }
        public string Param80 { get; set; }
        public string Param81 { get; set; }
        public string Param82 { get; set; }
        public string Param83 { get; set; }
        public string Param84 { get; set; }
        public string Param85 { get; set; }
        public string Param86 { get; set; }
        public string Param87 { get; set; }
        public string Param88 { get; set; }
        public string Param89 { get; set; }
        public string Param90 { get; set; }
        public string Param91 { get; set; }
        public string Param92 { get; set; }
        public string Param93 { get; set; }
        public string Param94 { get; set; }
        public string Param95 { get; set; }
        public string Param96 { get; set; }
        public string Param97 { get; set; }
        public string Param98 { get; set; }
        public string Param99 { get; set; }
        public string Param100 { get; set; }
        public string Module { get; set; }
        public int? LockedByUser { get; set; }
        public DateTime? CreatedOn { get; set; }
        public DateTime? UpdatedOn { get; set; }
        public int? UserId { get; set; }
    }
}
